name: Build

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and deploy 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build app 
        run: npm run build express-app-01
      - name: Deploy app 
        run: gcloud app deploy  
        working-directory: ./apps/express-app-01
